name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - frontend  # Runs on push to the frontend branch

jobs:
  build-and-deploy:
    name: Build, Test & Deploy Frontend
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Clean Install Dependencies
        run: |
          rm -rf node_modules
          rm package-lock.json
          npm install

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci  # Clean, reproducible installs
      - name: Clear Jest cache
        run: npx jest --clearCache
      

      - name: Print Installed Dependencies
        run: npm list --depth=0  # Verifies that dependencies are correctly installed
      - name: Check Jest Version
        run: npx jest --version

      - name: Run Jest Tests
        run: npm test
      - name: List directory contents
        run: |
          echo "Listing files and folders:"
          ls -R  # This lists all files and directories recursively in the current working directory

      - name: Upload JUnit Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: results/junit.xml

      - name: Upload HTML Report (if using Jest HTML Reporter)
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: results/test-report.html


      - name: Upload Jest Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-report
          path: coverage/


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Clean S3 Bucket
        run: |
          aws s3 rm s3://searchproject-frontend --recursive
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://searchproject-frontend \
          --exclude "node_modules/*" \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "*.test.mjs" \
          --exclude "package.json" \
          --exclude "package-lock.json" \
          --exclude "babel.config.mjs" \
          --exclude "jest.config.mjs" \
          --exclude "README.md" \
          --exclude ".*"  # Exclude dotfiles (if necessary)