name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - frontend  # Runs on push to the frontend branch

jobs:
  build-and-deploy:
    name: Build, Test & Deploy Frontend
    runs-on: ubuntu-latest  # Using Ubuntu for better Node.js compatibility

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensuring Node.js 18 is used

      - name: Install Dependencies
        run: npm ci  # Clean, reproducible installs

      - name: Print Installed Dependencies
        run: npm list --depth=0  # Verifies that dependencies are correctly installed

      - name: Run Tests
        run: npm test -- --verbose  # Runs tests with verbose output for detailed logs

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  

      - name: Deploy to S3
        run: aws s3 sync . s3://searchproject-frontend --exclude "node_modules/*" --exclude ".git/*" --exclude ".github/*" --exclude "*.test.js" --exclude "package.json" --exclude "package-lock.json"
